sudo:
  required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk11

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

script:
  - mvn -N io.takari:maven:wrapper
  - chmod +x ./mvnw
  - ./mvnw clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:

   #LOGIN
  - docker login -u $D_USER -p $D_PASS

   #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

   #VESTA-API
  - export VESTA_API=lindvior2/pad-lab
  - docker build -t $VESTA_API:$COMMIT ./
  - docker tag $VESTA_API:$COMMIT $VESTA_API:$TAG
  - docker push $VESTA_API

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'