sudo:
  required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk11

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

before_install:
  - mvn -N io.takari:maven:wrapper
  - chmod +x ./mvnw
  - ./mvnw clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:

   #LOGIN
  - docker login -u $D_USER -p $D_PASS
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

   #VESTA-API
  - export VESTA_API=lindvior2/pad-lab
  - docker build -t $VESTA_API:$COMMIT ./
  - docker tag $VESTA_API:$COMMIT $VESTA_API:$TAG registry.heroku.com/$HEROKU_APP/web
  - docker push $VESTA_API
  - docker push registry.heroku.com/$HEROKU_APP/web;
  - heroku container:release web --app $HEROKU_APP

#before_script:
#  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin   #login to dockerhub
#  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
#  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  #login to registry.heroku.com

#script:
#  - docker build -t aabhusan/koora:v1 .
#  - docker tag aabhusan/koora:v1 registry.heroku.com/$HEROKU_APP/web

#deploy:
#  provider: script
#  script:
#    docker push aabhusan/koora:v1;
#    docker push registry.heroku.com/$HEROKU_APP/web;
#    heroku container:release web --app $HEROKU_APP
#  on:
#    branch: master
cache:
  directories:
    - '$HOME/.m2/repository'
    - "$HOME/.cache"